
spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: sk-629a8fee757340abba3126fe80f0cc7b
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

logging:
  #  ??????
  level:
    org.springframework.ai.chat.client.advisor: debug
server:
  port: 16666