
spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: sk-225f3e59f9764cf58799598a92a1ff3e
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

logging:
  #  ??????
  level:
    org.springframework.ai.chat.client.advisor: debug
server:
  port: 16666